[package]
name = "nazoauthctl-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.104"
atomic-write-file = "0.3.1"
libc = "0.2.190"
nazo-operator-protocol.workspace = true
rand = "0.10.3"
rustix = { version = "1.1.5", features = ["fs", "process"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
wait-timeout = "0.2.1"
zeroize = { version = "1.9.0", features = ["derive"] }
uuid = { version = "1.27.0", features = ["v7"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_Memory",
] }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
